/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    tenders: Tender;
    posts: Post;
    careers: Career;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    tenders: TendersSelect<false> | TendersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'hi') | ('en' | 'hi')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'hi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for images used on the public site.
   */
  alt?: string | null;
  mediaType: 'image' | 'video' | 'lottie' | 'pdf' | 'html' | 'other';
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path without leading slash, e.g. "about" or "contact".
   */
  slug: string;
  /**
   * Compose the page from blocks. Shader variants map to your LightFX React components.
   */
  layout: (
    | {
        heading: string;
        subheading?: string | null;
        /**
         * Maps to HLLButton / GradientRevealText shader variant.
         */
        variant?:
          | (
              | 'services'
              | 'industries'
              | 'engagement'
              | 'about'
              | 'contact'
              | 'hll-ai'
              | 'hll-trust'
              | 'hll-foundation'
              | 'hll-ontology'
              | 'hll-people'
              | 'hll-application'
            )
          | null;
        revealSpeed?: ('slow' | 'normal') | null;
        backgroundImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        image: number | Media;
        caption?: string | null;
        fullWidth?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageBlock';
      }
    | {
        variant:
          | 'services'
          | 'industries'
          | 'engagement'
          | 'about'
          | 'contact'
          | 'hll-ai'
          | 'hll-trust'
          | 'hll-foundation'
          | 'hll-ontology'
          | 'hll-people'
          | 'hll-application';
        intensity?: number | null;
        placement?: ('full' | 'bottom') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'shaderSection';
      }
    | {
        /**
         * Upload a .json Lottie file (set Media type to Lottie).
         */
        animationFile: number | Media;
        label?: string | null;
        loop?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'lottieAnimation';
      }
    | {
        videoFile: number | Media;
        poster?: (number | null) | Media;
        autoplay?: boolean | null;
        muted?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'video';
      }
    | {
        /**
         * Legacy or migration HTML. Sanitize on the React frontend before render.
         */
        html: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'htmlEmbed';
      }
    | {
        label: string;
        href: string;
        variant?:
          | (
              | 'services'
              | 'industries'
              | 'engagement'
              | 'about'
              | 'contact'
              | 'hll-ai'
              | 'hll-trust'
              | 'hll-foundation'
              | 'hll-ontology'
              | 'hll-people'
              | 'hll-application'
            )
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        heading?: string | null;
        items?:
          | {
              title: string;
              description?: string | null;
              href?: string | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentGrid';
      }
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Shader / button color preset for this service page.
   */
  variant:
    | 'services'
    | 'industries'
    | 'engagement'
    | 'about'
    | 'contact'
    | 'hll-ai'
    | 'hll-trust'
    | 'hll-foundation'
    | 'hll-ontology'
    | 'hll-people'
    | 'hll-application';
  summary?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * HTML demos rendered inside the hero demo window. Each entry can map to a hero tab key.
   */
  demoWindow?: {
    /**
     * Label on the pill above the demo iframe.
     */
    selectorLabel?: string | null;
    /**
     * Optional per-tab demos. Set Tab key to match hero anchors (e.g. data-engineering).
     */
    demos?:
      | {
          tabKey: string;
          title?: string | null;
          contentType?: ('inline' | 'file') | null;
          /**
           * Full HTML document or fragment. Runs in a sandboxed iframe.
           */
          html?: string | null;
          /**
           * Upload a .html file (set Media type to HTML asset).
           */
          htmlFile?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Default HTML when no tab-specific demo matches.
     */
    fallbackHtml?: string | null;
    /**
     * Or upload a default .html demo file.
     */
    fallbackFile?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Maps to HLLButton / GradientRevealText shader variant.
             */
            variant?:
              | (
                  | 'services'
                  | 'industries'
                  | 'engagement'
                  | 'about'
                  | 'contact'
                  | 'hll-ai'
                  | 'hll-trust'
                  | 'hll-foundation'
                  | 'hll-ontology'
                  | 'hll-people'
                  | 'hll-application'
                )
              | null;
            revealSpeed?: ('slow' | 'normal') | null;
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            image: number | Media;
            caption?: string | null;
            fullWidth?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageBlock';
          }
        | {
            variant:
              | 'services'
              | 'industries'
              | 'engagement'
              | 'about'
              | 'contact'
              | 'hll-ai'
              | 'hll-trust'
              | 'hll-foundation'
              | 'hll-ontology'
              | 'hll-people'
              | 'hll-application';
            intensity?: number | null;
            placement?: ('full' | 'bottom') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'shaderSection';
          }
        | {
            /**
             * Upload a .json Lottie file (set Media type to Lottie).
             */
            animationFile: number | Media;
            label?: string | null;
            loop?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lottieAnimation';
          }
        | {
            videoFile: number | Media;
            poster?: (number | null) | Media;
            autoplay?: boolean | null;
            muted?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            /**
             * Legacy or migration HTML. Sanitize on the React frontend before render.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'htmlEmbed';
          }
        | {
            label: string;
            href: string;
            variant?:
              | (
                  | 'services'
                  | 'industries'
                  | 'engagement'
                  | 'about'
                  | 'contact'
                  | 'hll-ai'
                  | 'hll-trust'
                  | 'hll-foundation'
                  | 'hll-ontology'
                  | 'hll-people'
                  | 'hll-application'
                )
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  href?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentGrid';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders".
 */
export interface Tender {
  id: number;
  title: string;
  referenceNo: string;
  /**
   * e.g. Supply, Services, Construction
   */
  category?: string | null;
  summary?: string | null;
  expiryDate: string;
  /**
   * Set automatically after expiry via hook, or manually.
   */
  archived?: boolean | null;
  status?: ('draft' | 'published') | null;
  documents?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  corrigenda?:
    | {
        title: string;
        publishedAt?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  publishedAt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  slug: string;
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  expiryDate?: string | null;
  /**
   * Optional link to recruitment portal.
   */
  externalApplyUrl?: string | null;
  status?: ('draft' | 'published') | null;
  documents?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'tenders';
        value: number | Tender;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  mediaType?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              variant?: T;
              revealSpeed?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              fullWidth?: T;
              id?: T;
              blockName?: T;
            };
        shaderSection?:
          | T
          | {
              variant?: T;
              intensity?: T;
              placement?: T;
              id?: T;
              blockName?: T;
            };
        lottieAnimation?:
          | T
          | {
              animationFile?: T;
              label?: T;
              loop?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              videoFile?: T;
              poster?: T;
              autoplay?: T;
              muted?: T;
              id?: T;
              blockName?: T;
            };
        htmlEmbed?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contentGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  variant?: T;
  summary?: T;
  featuredImage?: T;
  demoWindow?:
    | T
    | {
        selectorLabel?: T;
        demos?:
          | T
          | {
              tabKey?: T;
              title?: T;
              contentType?: T;
              html?: T;
              htmlFile?: T;
              id?: T;
            };
        fallbackHtml?: T;
        fallbackFile?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              variant?: T;
              revealSpeed?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        imageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              fullWidth?: T;
              id?: T;
              blockName?: T;
            };
        shaderSection?:
          | T
          | {
              variant?: T;
              intensity?: T;
              placement?: T;
              id?: T;
              blockName?: T;
            };
        lottieAnimation?:
          | T
          | {
              animationFile?: T;
              label?: T;
              loop?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              videoFile?: T;
              poster?: T;
              autoplay?: T;
              muted?: T;
              id?: T;
              blockName?: T;
            };
        htmlEmbed?:
          | T
          | {
              html?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contentGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders_select".
 */
export interface TendersSelect<T extends boolean = true> {
  title?: T;
  referenceNo?: T;
  category?: T;
  summary?: T;
  expiryDate?: T;
  archived?: T;
  status?: T;
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  corrigenda?:
    | T
    | {
        title?: T;
        publishedAt?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  publishedAt?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  expiryDate?: T;
  externalApplyUrl?: T;
  status?: T;
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  /**
   * Primary navigation. Variant controls HLLButton colors.
   */
  headerNav?:
    | {
        label: string;
        href: string;
        variant?:
          | (
              | 'services'
              | 'industries'
              | 'engagement'
              | 'about'
              | 'contact'
              | 'hll-ai'
              | 'hll-trust'
              | 'hll-foundation'
              | 'hll-ontology'
              | 'hll-people'
              | 'hll-application'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('twitter' | 'facebook' | 'instagram' | 'linkedin' | 'youtube') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  headerNav?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}